# Generated by Django 5.2.1 on 2025-06-05 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="submission",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="student",
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={
                "ordering": ["start_time", "title"],
                "verbose_name": "Ujian",
                "verbose_name_plural": "Ujian",
            },
        ),
        migrations.RemoveField(
            model_name="exam",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_id",
        ),
        migrations.AddField(
            model_name="exam",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pembuat Ujian",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="duration_minutes",
            field=models.IntegerField(default=60, verbose_name="Durasi (menit)"),
        ),
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(null=True, verbose_name="Waktu Berakhir"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Waktu Mulai"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.CharField(
                default="Umum", max_length=100, verbose_name="Mata Pelajaran"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Deskripsi"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(
                default="Ujian Baru", max_length=200, verbose_name="Judul Ujian"
            ),
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Nomor Soal"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(default="Jelaskan...", verbose_name="Teks Soal"),
                ),
                (
                    "max_points",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Poin Maksimal"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_questions",
                        to="exams.exam",
                        verbose_name="Ujian Terkait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soal Esai",
                "verbose_name_plural": "Soal Esai",
                "ordering": ["exam", "question_number"],
                "unique_together": {("exam", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(default="", verbose_name="Teks Jawaban"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Waktu Dijawab"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="Nilai",
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(default=False, verbose_name="Sudah Dinilai"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.essayquestion",
                        verbose_name="Soal",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Siswa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jawaban Siswa",
                "verbose_name_plural": "Jawaban Siswa",
                "ordering": ["-submitted_at"],
                "unique_together": {("student", "question")},
            },
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
