# Generated by Django 5.2.1 on 2025-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_remove_grade_answer_remove_question_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="reference_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="exam_references/",
                verbose_name="Dokumen Referensi",
            ),
        ),
    ]
