# Generated by Django 5.2.1 on 2025-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_exam_reference_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="total_essay_questions",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Jumlah Soal Esai"
            ),
        ),
    ]
