# Generated by Django 5.2.1 on 2025-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_total_essay_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayquestion",
            name="answer_text",
            field=models.TextField(
                blank=True, default="", verbose_name="Kunci Jawaban Esai"
            ),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Terkunci"),
        ),
    ]
